# This file was automatically generated using `generate_pyton_classes.py` script.
# Please don't make any direct modifications to this file as they will be overwritten and lost in the next cycle.
# Instead please make modification in the respective .yaml file.
# Generated on 2023-10-06 23:18


class hub_config:
    GAUGE_COMM_HEADER_LEN = 9
    GAUGE_COMM_MAX_TX_DATA_LEN = 1000
    GAUGE_COMM_MAX_RX_DATA_LEN = 5000
    GAUGE_COMM_START_CHAR = '>'
    GAUGE_COMM_POS_CMD = 1
    GAUGE_COMM_POS_DATA_TYPE = 3
    GAUGE_COMM_POS_DATA_LENGTH_UPPER = 5
    GAUGE_COMM_POS_DATA_LENGTH_LOWER = 7
    GAUGE_COMM_POS_DATA_START = 9
    GAUGE_COMM_SERIAL_RX_TIMEOUT = 1000
    GAUGE_COMM_SERIAL_TX_TIMEOUT = 1000
    GAUGE_SERIAL_PROTOCOL_VERSION = "v1"
    GAUGE_SERIAL_JUMP_TO_BTL_KEY1 = 0x53
    GAUGE_SERIAL_JUMP_TO_BTL_KEY2 = 0x4B

class hub_commands:
    COMM_CMD_FIRST = 0x00
    COMM_CMD_SET_DIAL_RAW_SINGLE = 0x01
    COMM_CMD_SET_DIAL_RAW_MULTIPLE = 0x02
    COMM_CMD_SET_DIAL_PERC_SINGLE = 0x03
    COMM_CMD_SET_DIAL_PERC_MULTIPLE = 0x04
    COMM_CMD_SET_DIAL_CALIBRATE_MAX = 0x05
    COMM_CMD_SET_DIAL_CALIBRATE_HALF = 0x06
    COMM_CMD_GET_DEVICES_MAP = 0x07
    COMM_CMD_PROVISION_DEVICE = 0x08
    COMM_CMD_RESET_ALL_DEVICES = 0x09
    COMM_CMD_DIAL_POWER = 0x0A
    COMM_CMD_GET_DEVICE_UID = 0x0B
    COMM_CMD_RESCAN_BUS = 0x0C
    COMM_CMD_DISPLAY_CLEAR = 0x0D
    COMM_CMD_DISPLAY_GOTO_XY = 0x0E
    COMM_CMD_DISPLAY_IMG_DATA = 0x0F
    COMM_CMD_DISPLAY_SHOW_IMG = 0x10
    COMM_CMD_RX_BUFFER_SIZE = 0x11
    COMM_CMD_RESET_CFG = 0x12
    COMM_CMD_SET_RGB_BACKLIGHT = 0x13
    COMM_CMD_SET_DIAL_EASING_STEP = 0x14
    COMM_CMD_SET_DIAL_EASING_PERIOD = 0x15
    COMM_CMD_SET_BACKLIGHT_EASING_STEP = 0x16
    COMM_CMD_SET_BACKLIGHT_EASING_PERIOD = 0x17
    COMM_CMD_GET_EASING_CONFIG = 0x18
    COMM_CMD_GET_BUILD_INFO = 0x19
    COMM_CMD_GET_FW_INFO = 0x20
    COMM_CMD_GET_HW_INFO = 0x21
    COMM_CMD_GET_PROTOCOL_INFO = 0x22
    COMM_CMD_DEBUG_I2C_SCAN = 0xF3
    COMM_CMD_HUB_BTL_JUMP_TO_BOOTLOADER = 0xF4
    COMM_CMD_DIAL_BTL_JUMP_TO_BOOTLOADER = 0xF5
    COMM_CMD_DIAL_BTL_GET_INFO = 0xF6
    COMM_CMD_DIAL_BTL_GET_CRC = 0xF7
    COMM_CMD_DIAL_BTL_ERASE_APP = 0xF8
    COMM_CMD_DIAL_BTL_FWUP_SEND_PACKAGE = 0xF9
    COMM_CMD_DIAL_BTL_FWUP_FINISHED = 0xFA
    COMM_CMD_DIAL_BTL_EXIT = 0xFB
    COMM_CMD_DIAL_BTL_RESTART_FW_UPLOAD = 0xFC
    COMM_CMD_DIAL_BTL_READ_LAST_STATUS = 0xFD
    COMM_CMD_LAST = None

class hub_data_types:
    COMM_DATA_FIRST = 0x00
    COMM_DATA_NONE = 0x01
    COMM_DATA_SINGLE_VALUE = 0x02
    COMM_DATA_MULTIPLE_VALUE = 0x03
    COMM_DATA_KEY_VALUE_PAIR = 0x04
    COMM_DATA_MULTIPLE_KEY_VALUE = 0x04
    COMM_DATA_STATUS_CODE = 0x05
    COMM_DATA_LAST = None

class hub_status_codes:
    GAUGE_STATUS_OK = 0x0000
    GAUGE_STATUS_FAIL = 0x0001
    GAUGE_STATUS_BUSY = 0x0002
    GAUGE_STATUS_TIMEOUT = 0x0003
    GAUGE_STATUS_BAD_DATA = 0x0004
    GAUGE_STATUS_PROTOCOL_ERROR = 0x0005
    GAUGE_STATUS_NO_MEMORY = 0x0006
    GAUGE_STATUS_INVALID_ARGUMENT = 0x0007
    GAUGE_STATUS_BAD_ADDRESS = 0x0008
    GAUGE_STATUS_FORBIDDEN = 0x0009
    GAUGE_STATUS_ALREADY_EXISTS = 0x000B
    GAUGE_STATUS_UNSUPPORTED = 0x000C
    GAUGE_STATUS_NOT_IMPLEMENTED = 0x000D
    GAUGE_STATUS_MALFORMED_PACKAGE = 0x000E
    GAUGE_STATUS_RECURSIVE_CALL = 0x0010
    GAUGE_STATUS_DATA_MISMATCH = 0x0011
    GAUGE_STATUS_DEVICE_OFFLINE = 0x0012
    GAUGE_STATUS_MODULE_NOT_INIT = 0x0013
    GAUGE_STATUS_I2C_ERROR = 0x0014
    GAUGE_STATUS_USART_ERROR = 0x0015
    GAUGE_STATUS_SPI_ERROR = 0x0016
    GAUGE_STATUS_BTL_NO_DEVICE = 0xE001
    GAUGE_STATUS_BTL_INVALID_STATE = 0xE002
    GAUGE_STATUS_BTL_INVALID_REQUEST = 0xE003
