name: Create VU1 Server release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    release:
      types: [created, updated]

permissions:
  contents: write

jobs:
  Release:

    runs-on: windows-latest

    env:
      App_Packages_Archive: VU1_Server

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        update-environment: true
        cache: 'pip' # caching pip dependencies

    # Install python requirements
    - run: pip install -r requirements.txt

    # Create artifacts folder
    - name: Create Artifact Folder
      run: New-Item -Path '${{ github.workspace }}' -Name "Artifacts" -ItemType "directory"

    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Add version stamp
      run: |
        python3 ${{ github.workspace }}/make_version.py

    # PyInstaller
    - run: >
          pyinstaller.exe --name VUServer
          --distpath="${{ github.workspace }}/Artifacts"
          --clean
          --path="${{ github.workspace }}"
          --icon="www/favicon.ico"
          --add-data="config.yaml;."
          --add-data="www/assets/css/*;www/assets/css"
          --add-data="www/assets/img/*;www/assets/img"
          --add-data="www/assets/js/*;www/assets/js"
          --add-data="www/views/*;www/views"
          --add-data="www/*.png;www/"
          --add-data="www/*.html;www/"
          --add-data="www/*.ico;www/"
          --add-data="upload/img_blank;upload/"
          --uac-admin
          --noconsole
          server.py

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        path: VUServer
        directory: ${{ github.workspace }}\Artifacts
        filename: 'VUServer.zip'

    - run: dir ${{ github.workspace }}\Artifacts\VUServer
    - run: dir ${{ github.workspace }}\Artifacts
    - run: dir ${{ github.workspace }}

    # Create the release: https://github.com/softprops/action-gh-release
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.workspace }}\\Artifacts\\VUServer.zip"
        body: "Draft release"
        draft: true
        allowUpdates: true
