name: Build VU1 Server

on:
  push:
    branches:
    - 'build_*'
    - 'master'
    tags:
    - 'v*'
  pull_request:
    paths:
      - "**.py"
      - "www/**"
      - "upload/**"
      - "requirements*.txt"
      - ".github/workflows/pyinstaller.yaml"

jobs:
  Build:

    runs-on: windows-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: pip install -r requirements-build.txt

    - name: Add version stamp
      run: python make_version.py

    - run: >
          pyinstaller --name VUServer
          --distpath="${{ github.workspace }}/Artifacts"
          --clean
          --path="${{ github.workspace }}"
          --icon="www/favicon.ico"
          --add-data="config.yaml;."
          --add-data="www/assets/css/*;www/assets/css"
          --add-data="www/assets/img/*;www/assets/img"
          --add-data="www/assets/js/*;www/assets/js"
          --add-data="www/views/*;www/views"
          --add-data="www/*.html;www/"
          --add-data="www/*.ico;www/"
          --add-data="upload/img_blank;upload/"
          --uac-admin
          --noconsole
          server.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        name: VU1_Server
        path: ${{ github.workspace }}/Artifacts/VUServer/*
      if: ${{ always() }}

  Release:

    needs: Build
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v8
      with:
        name: VU1_Server
        path: VUServer

    - run: zip -r VUServer.zip VUServer

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: VUServer.zip
        body: "Draft release"
        draft: true
        allowUpdates: true
