name: Build VU1 Server

on:
  pull_request:
    paths:
      - "**.py"
      - "www/**"
      - "upload/**"
      - ".github/workflows/pyinstaller.yaml"

jobs:
  Installer:

    runs-on: windows-latest

    env:
      App_Packages_Archive: VU1_Server
      Solution_Path: VU1WPF
      Actions_Allow_Unsecure_Commands: true # Allows AddPAth and SetEnv commands

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        update-environment: true
        cache: 'pip' # caching pip dependencies

    # Install python requirements
    - run: pip install -r requirements.txt

    # Create artifacts folder
    - name: Create Artifact Folder
      run: New-Item -Path '${{ github.workspace }}' -Name "Artifacts" -ItemType "directory"

    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Add version stamp
      run: |
        python3 ${{ github.workspace }}/make_version.py

    # PyInstaller
    - run: >
          pyinstaller.exe --name VUServer
          --distpath="${{ github.workspace }}/Artifacts"
          --clean
          --path="${{ github.workspace }}"
          --icon="www/favicon.ico"
          --add-data="config.yaml;."
          --add-data="www/assets/css/*;www/assets/css"
          --add-data="www/assets/img/*;www/assets/img"
          --add-data="www/assets/js/*;www/assets/js"
          --add-data="www/views/*;www/views"
          --add-data="www/*.png;www/"
          --add-data="www/*.html;www/"
          --add-data="www/*.ico;www/"
          --add-data="upload/img_blank;upload/"
          --hiddenimport="pywin32"
          --hiddenimport="win32timezone"
          --uac-admin
          server.py

    # Upload build artifacts
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.App_Packages_Archive }}
        path: ${{ github.workspace }}/Artifacts/VUServer/*
      if: ${{ always() }}

    # Install NSIS
    - name: Install NSIS
      run: |
        choco install nsis

    - name: Create installer
      run: |
        makensis /DINSTALLEROUTPUT="${{ github.workspace }}\Artifacts\VU1-Installer.exe" /DDIRDIST="${{ github.workspace }}\Artifacts\VUServer" /DDIRSOURCE="${{ github.workspace }}" ${{ github.workspace }}\installer\install.nsi


    # Upload installer
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.App_Packages_Archive }}_installer.exe
        path: ${{ github.workspace }}/Artifacts/VU1-Installer.exe
      if: ${{ always() }}
