name: Pylint

on:
  push:
    paths:
      - "**.py"
      - "pylintrc"
      - ".github/workflows/pylint.yaml"
  pull_request:
    paths:
      - "**.py"
      - "pylintrc"
      - ".github/workflows/pylint.yaml"

jobs:
  PyLint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install pylint -r requirements-dev.txt
    - name: Run Pylint on code
      run: pylint --rc-file=pylintrc $(git ls-files '*.py')
